// Faz 1 kapsaminda kullanilan jenerik hata kodlari. Domain'e ozel hata
// kodlari (ATTACHMENT_ASSIGNMENT_MISMATCH, TICKET_STATUS_UNCHANGED vb.)
// ilgili domain servisleri implemente edildiginde tanimlanacaktir.
export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  AUTH_INVALID_OTP: 'AUTH_INVALID_OTP',
  AUTH_INVALID_REFRESH: 'AUTH_INVALID_REFRESH',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
  // Faz 3 (Facility + Membership + Users) — onaylanan Faz 3 plani Bolum 12.
  USER_PHONE_ALREADY_EXISTS: 'USER_PHONE_ALREADY_EXISTS',
  USER_PROFILE_CHANGE_FORBIDDEN: 'USER_PROFILE_CHANGE_FORBIDDEN',
  UNIT_NOT_FOUND: 'UNIT_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  FACILITY_NOT_FOUND: 'FACILITY_NOT_FOUND',
  FACILITY_CODE_CONFLICT: 'FACILITY_CODE_CONFLICT',
  FACILITY_INVALID_PARENT: 'FACILITY_INVALID_PARENT',
  SITE_NOT_FOUND: 'SITE_NOT_FOUND',
  RESIDENT_UNIT_ASSIGNMENT_CONFLICT: 'RESIDENT_UNIT_ASSIGNMENT_CONFLICT',
  RESIDENT_UNIT_ASSIGNMENT_NOT_FOUND: 'RESIDENT_UNIT_ASSIGNMENT_NOT_FOUND',
  // Faz 4 (Ticket cekirdegi) — onaylanan Faz 4 plani Bolum 17.
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  TICKET_UPDATE_FORBIDDEN: 'TICKET_UPDATE_FORBIDDEN',
  TICKET_UPDATE_EMPTY: 'TICKET_UPDATE_EMPTY',
  TICKET_STATUS_UNCHANGED: 'TICKET_STATUS_UNCHANGED',
  TICKET_INVALID_STATUS_TRANSITION: 'TICKET_INVALID_STATUS_TRANSITION',
  TICKET_TRANSITION_FORBIDDEN: 'TICKET_TRANSITION_FORBIDDEN',
  TICKET_TRANSITION_REASON_REQUIRED: 'TICKET_TRANSITION_REASON_REQUIRED',
  CONCURRENT_MODIFICATION: 'CONCURRENT_MODIFICATION',
  TICKET_SITE_CONTRACT_INACTIVE: 'TICKET_SITE_CONTRACT_INACTIVE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
